harnessApiVersion: '1.0'
type: CONFIG_FILE
checksum: 8c6a9179e8dc163cdc80fff8198e3741
checksumType: MD5
encrypted: false
fileName: configs_Abaris.properties
targetFilePath: configs/Abaris.properties
targetToAllEnv: false
